matrix:
  include:
    - IMAGE: rust:alpine
      TARGET: x86_64-unknown-linux-musl
      PKG_UPDATE: apk update
      PKG_INSTALL: apk add --no-cache musl-dev
    - IMAGE: rust:latest
      TARGET: x86_64-unknown-linux-gnu
      PKG_UPDATE: apt-get update
      PKG_INSTALL: apt-get install -y gcc

steps:
  test:
    image: ${IMAGE}
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - ${PKG_UPDATE}
      - ${PKG_INSTALL}
      - rustup target add ${TARGET}
      - cargo test --target ${TARGET}
      - rustup component add clippy
      - cargo clippy --target ${TARGET} -- -D warnings

  build:
    image: ${IMAGE}
    when:
      event: tag
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - ${PKG_UPDATE}
      - ${PKG_INSTALL}
      - rustup target add ${TARGET}
      - cargo build --profile optimized --target ${TARGET}
      - tar -zcvf file-rs-${TARGET}.tar.gz -C target/${TARGET}/optimized file-rs

  publish:
    image: woodpeckerci/plugin-gitea-release
    when:
      event: tag
    settings:
      base_url: https://codeberg.org
      files:
        - "hc-rs-${TARGET}.tar.gz"
      api_key:
        from_secret: CODEBERG_ACCESS_TOKEN
      title: ${CI_COMMIT_TAG}
      # skip_verify: true # Only use if Codeberg SSL is flaky
